kind: pipeline
type: docker
name: test

steps:
  - name: Test Node
    image: satantime/puppeteer-node:25-trixie-slim
    commands:
      - apt-get update && apt-get install -y curl xz-utils zip
      - curl https://qlty.sh | sh
      - curl -fsSL https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
      - export PNPM_HOME="$HOME/.local/share/pnpm" && export PATH="$PNPM_HOME:$PATH"
      - pnpm install
      - pnpm run package
      - pnpm test
      - ~/.qlty/bin/qlty coverage publish .coverage/clover.xml --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_qH9pUuLeBSudET4U
