kind: pipeline
type: docker
name: test

steps:
  - name: Test Node
    image: satantime/puppeteer-node:24-trixie-slim
    commands:
      - apt-get update && apt-get install -y curl xz-utils zip
      - curl https://qlty.sh | sh
      - npm ci
      - npm run package
      - npm test
      - ~/.qlty/bin/qlty coverage publish .coverage/clover.xml --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_qH9pUuLeBSudET4U

  - name: Publish Node
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    image: node:24
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" > ~/.npmrc
      - npm whoami
      - npm publish
    depends_on:
      - Test Node
    when:
      event:
        - tag
